### ISSUE TITLE
Puppeteer calls are 404ing

### ISSUE THREAD

**Issue by Eelesy** [GoogleChromeLabs/chrome-for-testing#109]
Hi, 

As of this morning my calls using npx @puppeteer/browsers install chrome@stable result in a 404 error to the edgedl.me urls. Any one else seeing this issue? My scripts are all broken as I cannot get the latest CfT version.

Thanks.

**Comment by sfitzsimmons-tractioncomplete** [comment]
I'm not a contributor and don't have more details on the problem, but we're having the same issue and all our CI is also now down due to this issue. 
 
As a potential workaround that may work for some people's use cases, it appears that ironically enough, chrome for testing "stable" is down, but "dev" is still working, so we're currently putting emergency PRs through on all our projects to move from stable to dev as a workaround for the time being.

**Comment by bigcharl** [comment]
(https://github.com/GoogleChromeLabs/chrome-for-testing/pull/108#issue-2136148704)

not sure what's going on here but I changed the endpoint from the edgedl(which is legacy?) to the storage.googleapis and it did the trick for my selenium

```
zip_name = zip_name.replace("_", "-", 1)
# download_url = "https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/%s/%s/%s"
download_url = 'https://storage.googleapis.com/chrome-for-testing-public/%s/%s/%s'
download_url %= (self.version_full.vstring, self.platform_name, zip_name)
```

**Comment by rileyshanahan20** [comment]
@mathiasbynens I'm also seeing 500 failures when downloading Puppeteer when trying to download any URL with the `edgedl` domain. We can't simply change to using the new download URL because other packages we depend on and install are still using the `edgedl` URL. 

If this is the same ticket, what's the status of this ticket? This is pretty disruptive.

**Comment by alexsch01** [comment]
> Since you asked, I’ll elaborate on the details: the final step in the abovementioned hosting solution migration is to set up redirects from the old base URL `https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/*` to the new location `https://storage.googleapis.com/chrome-for-testing-public/*`. This way, even old software that hardcodes the old base URL would still be able to get downloads for newer version numbers.

example of a URL that still 404s: https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/121.0.6167.184/linux64/chrome-linux64.zip

**Comment by ilicmarko** [comment]
@mathiasbynens Is there an update on this issue? This is a major breaking change that is currently blocking any pipeline that uses the Chrome browser.

When I run `npx @puppeteer/browsers install chrome@stable` I still get a 404, we use this inside the pipeline to setup puppeteer inside the CI. 

```
Error: Download failed: server returned code 404. URL: https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/124.0.6367.91/mac-arm64/chrome-mac-arm64.zip
```

**Comment by mathiasbynens** [comment]
**Updating to the latest `@puppeteer/browsers` should address this**, so I’m closing this issue.

More background: we’ve enabled server-side redirects multiple times now but every time there was unexpected breakage (incl. in Puppeteer itself at first). For this reason, we’ve disabled redirects for now, but we plan on taking another look in 2024Q3 in hopes we can re-enable redirects again (b/330111501).
