### ISSUE TITLE
Could not start a new session. Response code 500

### ISSUE THREAD

**Issue by gtach2o** [GoogleChromeLabs/chrome-for-testing#26]
Hi!
After driver update it can't start the browser.
Previous driver version 114.0.5735.90 works with no issue. 
```
	Suppressed: org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: unknown error: cannot find Chrome binary 
Build info: version: '4.10.0', revision: 'c14d967899'
System info: os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '13.4.1', java.version: '20.0.1'
```

Chrome version - 115.0.5790.98
Chromedriver version - 115.0.5790.98

**Comment by diemol** [comment]
This seems more like an issue in Selenium, please create an issue at https://github.com/SeleniumHQ/selenium

**Comment by gtach2o** [comment]
How it can be Selenium issue if previous driver works just fine?

**Comment by mathiasbynens** [comment]
The HTTP endpoints to figure out which browser binary maps to which driver binary are changing starting with M115+, indeed. The good news is you may not need to do any kind of version-mapping yourself anymore, since every user-facing Chrome release now comes with a Chrome for Testing binary + a ChromeDriver binary with exactly the same version.

More details: https://groups.google.com/g/chromedriver-users/c/qVPTFXnedw0

**Comment by gtach2o** [comment]
I don't have any issue with matching Chrome version with driver version.
What I'm saying is driver 115.0.5790.98 is not able to start Chrome browser 115.0.5790.98

**Comment by gtach2o** [comment]
Continue in https://github.com/SeleniumHQ/selenium/issues/12381

**Comment by gtach2o** [comment]
@diemol So, this is the driver issue not Selenium
https://github.com/GoogleChromeLabs/chrome-for-testing/issues/30#issuecomment-1643668565
