### ISSUE TITLE
Chromedriver v118 flagged by security software as malicious

### ISSUE THREAD

**Issue by kretschmannj** [GoogleChromeLabs/chrome-for-testing#68]
The zip file for chromedriver v118 is being flagged by our security software as malicious.  The URL in question is ...

https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/118.0.5993.70/win64/chromedriver-win64.zip

... and the issues found include ...

_The file hash's of the program itself appear in VirusTotal as malicious.  The EXE requests PowerShell to run, then asks PowerShell to execute another program, this is suspicious.  There is an imbedded email address in the zip file (info@e-szigno.hu) that is associated with Hungary, that is suspicious._

**Comment by mathiasbynens** [comment]
This sounds like a problem with the security software rather than with ChromeDriver or Chrome for Testing.

(The email address you mention is [part of a root store certificate shipping with Chrome](https://source.chromium.org/chromium/chromium/src/+/main:net/data/ssl/chrome_root_store/root_store.certs;l=6594;drc=1950592832c759b7f7a21d209d458a89b7b9dcd3) — nothing malicious.)

**Comment by kretschmannj** [comment]
Thanks.  I'm working back with our security team on this.  What about the other issues flagged ... 

- The file hash's of the program itself appear in VirusTotal as malicious
- The EXE requests PowerShell to run, then asks PowerShell to execute another program, this is suspicious
